# Site settings
title: EIC | East India Comedy - Stand up comedy, Branding and Digital Content
email:
author:
description:
url:

# Build settings
permalink: :title/
sass:
  sass_dir: css

collections:
  profiles:
    output: true
    